steps:
- bash: |
    echo ""
    echo "--------------------------------"
    echo "Confirm Key Vault üîë Integration"
    echo "--------------------------------"
    echo "KV_DEBUG_ENV: $KV_DEBUG_ENV"
    echo ""
    if [ "$KV_DEBUG_ENV" = '$(kv-debug-env)' ]; then
      echo "‚õîÔ∏è Key Vault not loaded"
      echo "Please double check configuration Variable Groups in Azure Pipelines UI and that the YAML pipeline is running against the 'main' or 'production' branch."
      exit 1
    else
      echo "‚úÖ Key Vault loaded"
    fi
  displayName: Debug - Key Vault loaded?
  env:
    KV_DEBUG_ENV: $(kv-debug-env)

